name: story_viewer
description: This package provides common story view experience for any Flutter app.
version: 0.0.19
homepage: https://github.com/furkansarihan/story_viewer

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  extended_image: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
